12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Models/PhongBan/PhongBanView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations; 
namespace QLNV_Web.Models.PhongBan
{
    public class PhongBanView
    {
        public int ID { get; set; }
        [Display(Name = "Mã phòng ban")]
        public string MaPhongBan { get; set; }
        [Display(Name ="Tên phòng ban ")]
        public string TenPhongBan { get; set; }
        [Display(Name = "Tổng số nhân viên ")]
        public int TongSoNhanVien { get; set; }
    }
}

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Models/PhongBan/SuaPhongBan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace QLNV_Web.Models.PhongBan
{
    public class SuaPhongBan
    {
        public int Id { get; set; }
        [Display(Name = "Mã phòng ban")]
        [Required(ErrorMessage = "Bạn phải nhập mã phòng ban")]
        [StringLength(maximumLength: 5, ErrorMessage = "Mã phòng ban phải có 5 kí tự")]
        [ReadOnly(true)]
        public string MaPhongBan { get; set; }
        [Display(Name = "Tên phòng ban ")]
        [Required(ErrorMessage = "Bạn phải nhập tên phòng ban")]
        [StringLength(maximumLength: 50, MinimumLength = 1, ErrorMessage = "Tên phòng ban từ 1 đến 50 kí tự")]
        public string TenPhongBan { get; set; }
    }
}

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Models/PhongBan/TaoPhongBan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace QLNV_Web.Models.PhongBan
{
    public class TaoPhongBan
    {
        [Display(Name = "Mã phòng ban")]
        [Required(ErrorMessage = "Bạn phải nhập mã phòng ban")]
        [StringLength(maximumLength:5,ErrorMessage ="Mã phòng ban phải có 5 kí tự")]
        public string MaPhongBan { get; set; }
        [Display(Name = "Tên phòng ban ")]
        [Required(ErrorMessage = "Bạn phải nhập tên phòng ban")]
        [StringLength(maximumLength: 50, MinimumLength =1, ErrorMessage = "Tên phòng ban từ 1 đến 50 kí tự")]
        public string TenPhongBan { get; set; }
       
    }
}

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using QLNV_Web.Models.NhanVien;
using QLNV_Web.Models.PhongBan;

namespace QLNV_Web.Controllers
{
    public class NhanVienController : Controller
    {
        private static int phongBanId = 0;
        public IActionResult Index(int id)
        {

            var nhanviens = new List<NhanVienView>();
            var url = $"{Common.Common.ApiUrl}/nhanvien/danhsachnhanvientheophongban/{id}";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                nhanviens = JsonConvert.DeserializeObject<List<NhanVienView>>(responseData);
            }
            phongBanId = id;
            ViewBag.TenPhongBan = DanhSachPhongBan().Where(p => p.ID == id).FirstOrDefault().TenPhongBan;
            return View(nhanviens);
        }
        public IActionResult TaoNhanVien()
        {
            ViewBag.Phongbans = DanhSachPhongBan();
            ViewBag.PhongBanId = phongBanId;
            return View();
        }

        [HttpPost]
        public IActionResult TaoNhanVien(TaoNhanVien model)
        {
            int ketQua = 0;
            var url = $"{Common.Common.ApiUrl}/nhanvien/taonhanvien";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";
            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                var json = JsonConvert.SerializeObject(model);
                streamWriter.Write(json);
            }
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                var resKetQua = streamReader.ReadToEnd();
                ketQua = int.Parse(resKetQua);
            }
            if (ketQua > 0)
            {
                TempData["ThanhCong"] = "Đã tạo nhân viên thành công";
            }
            ModelState.Clear();
            ViewBag.Phongbans = DanhSachPhongBan();
            ViewBag.PhongBanId = phongBanId;
            return View(new TaoNhanVien() { });
        }

        public IActionResult SuaNhanVien(int id)
        {
            var phongban = new SuaPhongBan();
            var url = $"{Common.Common.ApiUrl}/nhanvien/suanhanvien";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                phongban = JsonConvert.DeserializeObject<SuaPhongBan>(responseData);
            }
            TempData["ThanhCong"] = null;
            TempData["Loi"] = null;
            return View(phongban);
        }
        // ViewBag tên danh sách phòng ban
        private List<PhongBanItem> DanhSachPhongBan()
        {
            var phongbans = new List<PhongBanItem>();
            var url = $"{Common.Common.ApiUrl}/phongban/danhsachphongban";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                phongbans = JsonConvert.DeserializeObject<List<PhongBanItem>>(responseData);
            }
            return phongbans;
        }
    }
}

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Controllers/PhongBanController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QLNV_Web.Models;
using QLNV_Web.Models.PhongBan;
using System.Net;
using System.IO;
using Newtonsoft.Json;

namespace QLNV_Web.Controllers
{
    public class PhongBanController : Controller
    {
        public IActionResult Index()
        {
            var phongbans = new List<PhongBanView>();
            var url = $"{Common.Common.ApiUrl}/phongban/danhsachphongban";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                phongbans = JsonConvert.DeserializeObject<List<PhongBanView>>(responseData);
            }
            return View(phongbans);
        }

        public IActionResult TaoPhongBan()
        {

            TempData["ThanhCong"] = null;
            return View();
        }

        [HttpPost]
        public IActionResult TaoPhongBan(TaoPhongBan model)
        {
            int ketQua = 0;
            var url = $"{Common.Common.ApiUrl}/phongban/taophongban";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";
            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                var json = JsonConvert.SerializeObject(model);
                streamWriter.Write(json);
            }
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                var resKetQua = streamReader.ReadToEnd();
                ketQua = int.Parse(resKetQua);
            }
            if (ketQua > 0)
            {
                TempData["ThanhCong"] = "Đã tạo phòng ban thành công";
            }
            ModelState.Clear();
            return View(new TaoPhongBan() { });
        }

        public IActionResult SuaPhongBan(int id)
        {
            var phongban = new SuaPhongBan();
            var url = $"{Common.Common.ApiUrl}/phongban/layphongban/{id}";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "GET";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                phongban = JsonConvert.DeserializeObject<SuaPhongBan>(responseData);
            }
            TempData["ThanhCong"] = null;
            TempData["Loi"] = null;
            return View(phongban);
        }

        [HttpPost]
        public IActionResult SuaPhongBan(SuaPhongBan model)
        {
            int ketQua = 0;
            var url = $"{Common.Common.ApiUrl}/phongban/suaphongban";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "PUT";
            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                var json = JsonConvert.SerializeObject(model);
                streamWriter.Write(json);
            }
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                var resKetQua = streamReader.ReadToEnd();
                ketQua = int.Parse(resKetQua);
            }
            if (ketQua > 0)
            {
                TempData["ThanhCong"] = "Đã cập nhật phòng ban thành công";
            }
            else
            {
                TempData["Loi"] = "Không thể cập nhật phòng ban";
            }
            return View(new SuaPhongBan() { });
        }

        public IActionResult XoaPhongBan(int id)
        {
            var ketQua = false;
            var url = $"{Common.Common.ApiUrl}/phongban/xoaphongban/{id}";
            // gọi qua đường dẫn tạo 1 request với đường dẫn
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.Method = "DELETE";
            var response = httpWebRequest.GetResponse();
            {
                string responseData;
                Stream responseStream = response.GetResponseStream();
                try
                {
                    StreamReader streamReader = new StreamReader(responseStream);
                    try
                    {
                        responseData = streamReader.ReadToEnd();
                    }
                    finally
                    {
                        ((IDisposable)streamReader).Dispose();
                    }
                }
                finally
                {
                    ((IDisposable)responseStream).Dispose();
                }
                ketQua = JsonConvert.DeserializeObject<bool>(responseData);
            }
            return RedirectToAction("Index", "PhongBan");
        }
    }
}

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Views/PhongBan/Index.cshtml
@model IEnumerable<QLNV_Web.Models.PhongBan.PhongBanView>

@{
    ViewData["Title"] = "Phòng ban";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a class="btn btn-primary" asp-controller="PhongBan" asp-action="TaoPhongBan">Tạo phòng ban</a>
</p>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaPhongBan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenPhongBan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TongSoNhanVien)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.MaPhongBan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenPhongBan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TongSoNhanVien)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "SuaPhongBan", "PhongBan", new {  id=item.ID  }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Nhân viên", "Index", "NhanVien", new {  id=item.ID }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Xóa", "XoaPhongBan",
                                          new {  id=item.ID}, 
                                          new { @class = "btn btn-danger", onclick= "return confirm('Bạn có muốn xóa phòng ban này không?')" })
                </td>
            </tr>
        }
    </tbody>
</table>

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Views/PhongBan/SuaPhongBan.cshtml
@model QLNV_Web.Models.PhongBan.SuaPhongBan

@{
    ViewData["Title"] = "SuaPhongBan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sửa phòng ban</h1>
<div>
    <a class="btn btn-primary" asp-controller="PhongBan" asp-action="Index">Danh sách phòng ban</a>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SuaPhongBan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["ThanhCong"] != null)
            {
                <p class="btn btn-success">@TempData["ThanhCong"]</p>
            }
            @if (TempData["Loi"] != null)
            {
                <p class="btn btn-danger">@TempData["ThanhCong"]</p>
            }
            <div class="form-group">
                <label asp-for="MaPhongBan" class="control-label"></label>
                <input asp-for="MaPhongBan" class="form-control" />
                <span asp-validation-for="MaPhongBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenPhongBan" class="control-label"></label>
                <input asp-for="TenPhongBan" class="form-control" />
                <span asp-validation-for="TenPhongBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cập nhật" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

12_NetCore/API_QLNhanVien/QLNV_Web/QLNV_Web/Views/PhongBan/TaoPhongBan.cshtml
@model QLNV_Web.Models.PhongBan.TaoPhongBan

@{
    ViewData["Title"] = "TaoPhongBan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tạo phòng ban</h1>
<div>
    <a class="btn btn-primary" asp-controller="PhongBan" asp-action="Index">Danh sách phòng ban</a>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="PhongBan" method="post" asp-action="TaoPhongBan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if(TempData["ThanhCong"] != null){
            <p class="btn btn-success">@TempData["ThanhCong"]</p>
            }
            <div class="form-group">
                <label asp-for="MaPhongBan" class="control-label"></label>
                <input asp-for="MaPhongBan" class="form-control" />
                <span asp-validation-for="MaPhongBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenPhongBan" class="control-label"></label>
                <input asp-for="TenPhongBan" class="form-control" />
                <span asp-validation-for="TenPhongBan" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}